spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

server.port=${SERVER_PORT:8081}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.include-exception=false